name: Testi
on: [push]
jobs:
  ekatesti:
    runs-on: ubuntu-latest
    steps:
      - name: Komento
        run: |
          echo "Commit on $github.event.head_commit.message"
          echo "The nam eis ${{vars.MY_NAME}}"

          
