name: Testi
on: [workflow_dispatch]
jobs:
  ekatesti:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
            fetch-depth: 0
      - name: Komento
        run: |
          touch logi.txt
          git log --oneline > logi.txt
      - run: cat logi.txt
          
